"""empty message

Revision ID: 12db737e7f20
Revises: 9a87ee94f7ba
Create Date: 2019-02-09 08:28:06.704051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12db737e7f20'
down_revision = '9a87ee94f7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('phone_no', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stars')
    op.drop_column('user', 'phone_no')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
