"""empty message

Revision ID: 2081224efc0d
Revises: 9afd2fa144ec
Create Date: 2019-02-11 06:15:11.486857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2081224efc0d'
down_revision = '9afd2fa144ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpost', sa.Column('impressions', sa.Text(), nullable=True))
    op.drop_column('jobpost', 'impressions_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpost', sa.Column('impressions_list', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('jobpost', 'impressions')
    # ### end Alembic commands ###
