"""empty message

Revision ID: 3d2ba338d7aa
Revises: eb05f15341bd
Create Date: 2019-03-14 08:50:57.975253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2ba338d7aa'
down_revision = 'eb05f15341bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume_loc', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'resume_loc')
    # ### end Alembic commands ###
