"""empty message

Revision ID: 4b1c77f6ff57
Revises: d72dd93fe43d
Create Date: 2019-03-18 14:36:59.142967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1c77f6ff57'
down_revision = 'd72dd93fe43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('received', sa.String(length=120), nullable=True))
    op.add_column('feedback', sa.Column('sent', sa.String(length=120), nullable=True))
    op.drop_constraint('feedback_received_from_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_sent_from_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'user', ['received'], ['email'])
    op.create_foreign_key(None, 'feedback', 'user', ['sent'], ['email'])
    op.drop_column('feedback', 'sent_from')
    op.drop_column('feedback', 'received_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('received_from', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('sent_from', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_sent_from_fkey', 'feedback', 'user', ['sent_from'], ['email'])
    op.create_foreign_key('feedback_received_from_fkey', 'feedback', 'user', ['received_from'], ['email'])
    op.drop_column('feedback', 'sent')
    op.drop_column('feedback', 'received')
    # ### end Alembic commands ###
