"""add application

Revision ID: 4c7136127220
Revises: c069f691c9cb
Create Date: 2019-02-08 13:23:36.032422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7136127220'
down_revision = 'c069f691c9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_application_timestamp'), 'application', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_timestamp'), table_name='application')
    op.drop_column('application', 'timestamp')
    # ### end Alembic commands ###
