"""empty message

Revision ID: 616e44f531b7
Revises: 0652eaa5d350
Create Date: 2019-03-06 06:55:32.461327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616e44f531b7'
down_revision = '0652eaa5d350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'keywords')
    # ### end Alembic commands ###
