"""empty message

Revision ID: 9a87ee94f7ba
Revises: 4c7136127220
Create Date: 2019-02-08 13:51:50.324343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a87ee94f7ba'
down_revision = '4c7136127220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'status')
    # ### end Alembic commands ###
