"""empty message

Revision ID: 9afd2fa144ec
Revises: 12db737e7f20
Create Date: 2019-02-11 05:30:48.254903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afd2fa144ec'
down_revision = '12db737e7f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpost', sa.Column('impressions_list', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobpost', 'impressions_list')
    # ### end Alembic commands ###
