"""empty message

Revision ID: a92edfa11544
Revises: 6267ef4a2f30
Create Date: 2019-02-06 12:51:40.223840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92edfa11544'
down_revision = '6267ef4a2f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('organization', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'organization')
    # ### end Alembic commands ###
