"""empty message

Revision ID: c069f691c9cb
Revises: 23a33503874f
Create Date: 2019-02-08 13:11:23.526359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c069f691c9cb'
down_revision = '23a33503874f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('pay', sa.Integer(), nullable=True),
    sa.Column('pay_frequency', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobpost_timestamp'), 'jobpost', ['timestamp'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobpost_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobpost_id'], ['jobpost.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_job_post_timestamp', table_name='job_post')
    op.drop_table('job_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('pay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pay_frequency', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], name='job_post_email_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_post_pkey')
    )
    op.create_index('ix_job_post_timestamp', 'job_post', ['timestamp'], unique=False)
    op.drop_table('application')
    op.drop_index(op.f('ix_jobpost_timestamp'), table_name='jobpost')
    op.drop_table('jobpost')
    # ### end Alembic commands ###
