"""empty message

Revision ID: c499eeacda58
Revises: 
Create Date: 2019-03-26 12:44:58.936597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c499eeacda58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('phone_no', sa.Integer(), nullable=True),
    sa.Column('resume_loc', sa.String(length=1000), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.String(length=120), nullable=True),
    sa.Column('received', sa.String(length=120), nullable=True),
    sa.Column('feedback_msg', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['received'], ['user.email'], ),
    sa.ForeignKeyConstraint(['sent'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('pay', sa.FLOAT(precision=10), nullable=True),
    sa.Column('pay_frequency', sa.String(length=32), nullable=True),
    sa.Column('impressions', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobpost_timestamp'), 'jobpost', ['timestamp'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobpost_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('reject_reason', sa.String(length=32), nullable=True),
    sa.Column('feedback_given', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['jobpost_id'], ['jobpost.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_timestamp'), 'application', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_timestamp'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_jobpost_timestamp'), table_name='jobpost')
    op.drop_table('jobpost')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
