"""empty message

Revision ID: d72dd93fe43d
Revises: e844b582f51c
Create Date: 2019-03-18 14:30:30.610916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72dd93fe43d'
down_revision = 'e844b582f51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_from', sa.String(length=120), nullable=True),
    sa.Column('received_from', sa.String(length=120), nullable=True),
    sa.Column('feedback_msg', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['received_from'], ['user.email'], ),
    sa.ForeignKeyConstraint(['sent_from'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
