"""empty message

Revision ID: e844b582f51c
Revises: 3d2ba338d7aa
Create Date: 2019-03-18 14:28:30.430964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e844b582f51c'
down_revision = '3d2ba338d7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
